import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HeaderTopBar from './components/HeaderTopBar'
import Footer from './components/Footer'
import { Josefin_Sans } from 'next/font/google'
import HeaderMenu from './components/HeaderMenu'
import { CartProvider } from '@/app/context/CartContext'
import Script from 'next/script'

const josefin_init = Josefin_Sans({
  subsets: ["latin"],
  weight: ["100", "300", "700"],
  variable: "--font--josefin--"
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link
          rel="stylesheet"
          href={process.env.BASE_URL + `css/snipcart.css`}
        />
        <link rel="shortcut icon" href="../public/favicon.ico" />
        {/* Loading snipcart script asynchronously */}
        <Script
          src={process.env.BASE_URL + `js/snipcart.js`}
          strategy="afterInteractive"
        />
      </head>
      <body className={josefin_init.variable}>
        <CartProvider>
          <HeaderTopBar />
          <HeaderMenu />
          {children}
          <Footer />
          <div
            hidden
            id="snipcart"
            data-api-key={process.env.NEXT_PUBLIC_SNIPCART}
            data-config-modal-style="side"
            data-config-add-product-behavior=""
          ></div>
        </CartProvider>
      </body>
    </html>
  )
}
