import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import  HeaderTopBar  from './components/HeaderTopBar'
import  Footer  from './components/Footer'
import { Josefin_Sans } from 'next/font/google'
import HeaderMenu from './components/HeaderMenu'
import { CartProvider } from '@/app/context/CartContext';

const josefin_init = Josefin_Sans({
  subsets:["latin"],
  weight:["100", "300", "700"],
  variable:"--font--josefin--"
});

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={josefin_init.variable}>
      <CartProvider>
        <HeaderTopBar />
        <HeaderMenu/>
        {children}
        <Footer/>
      </CartProvider>
        </body>
    </html>
  )
}
